tracking:
  - path: /etc/example/config.yml
    events:
      - modify
    pipeline:
      reactor: 
        - name: hash_changed
          args:
            algoritm: sha256
          actions:
            - name: write_vault
              args:
                secret_path: secret/example/config
                secret_name: <file name>
  - path: /etc/example/configs
    type: directory
    file_name_filter: "*.yml|*.yaml"
    events:
      - modify
      - create
    pipeline:
      reactor: 
        - name: hash_changed
          args:
            algoritm: sha256
          actions:
            - name: write_vault
              args:
                secret_path: secret/example/config
                secret_name: <file_name>
