tracking:
  - path: /tmp/example/config.yml
    events:
      - modify
    pipeline:
      event_queue_size: 5
      reactor: 
        - name: hash-changed
          args:
            algorithm: sha256
          actions:
            - name: hello-action
              args:
                test_args: "test_value"
  - path: /tmp/example/configs
    type: directory
    file_name_filter: '\.crt$'
    events:
      - modify
      - create
    pipeline:
      event_queue_size: 5
      reactor: 
        - name: hash-changed
          args:
            algorithm: sha256
          actions:
            - name: hello-action
              args:
                hello-text: "This is hello action"
            - name: archive-file
              args:
                archive-destination: /tmp/inotify-archive-files/
                with-file-extensions:
                  - ".key"
