tracking:
  - path: /tmp/example/config.yml
    events:
      - modify
    pipeline:
      event_queue_size: 5
      reactor: 
        - name: hash-changed
          args:
            algorithm: sha256
          actions:
            - name: hello-action
              args:
                test_args: "test_value"
  - path: /tmp/example/configs
    type: directory
    file_name_filter: '\.yml$'
    events:
      - modify
      - create
    pipeline:
      reactor: 
        - name: hash-changed
          args:
            algorithm: sha256
          actions:
            - name: write_vault
              args:
                secret_path: secret/example/config
                secret_name: <file_name>
